import Head from 'next/head'
import Image from 'next/image'
import Form from '../components/Form'
import Header from '../components/Header'
import TopCard from '../components/TopCard'
import styles from '../styles/Home.module.css'
import self from '../assets/self-serve.png'
import money from '../assets/money.png'
import speed from '../assets/speed.png'
import  mic from '../assets/mic.png'
import Banner from '../components/Banner'
import Barnds from '../components/Barnds'
import artoon from '../assets/artoon.png'
import collect from '../assets/collect.png'
import affel from '../assets/affel.png'
import inmobi from '../assets/inmobi.png'
import gala from '../assets/gala.png'
import jump from '../assets/jump.png'
import Testo from '../components/Testo'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <main className={styles.main}>
        <div className={styles.topSec}>
          <div className={styles.topSec_title}>
            <span className={styles.underline}>Result-oriented</span> <br/>
          performance campaigns<br/> for every objective
          </div>
           <div className={styles.cardContainer}>
              <TopCard
              img={self}
              text="Self-serve platform with CPI starting at INR 1"
              />
              <TopCard
              img={money}
              text="Access to premium inventory and exposure to 5K+ apps"
              />
              <TopCard
              img={speed}
              text="Comprehensive reporting and insights into campaign performance"
              />
              <TopCard
              img={mic}
              text="Campaigns for every need - clicks, installs, impressions, and more"
              />
           </div>
           <Form/>
        </div>
        <Banner/>
        <Barnds>
          <div className={styles.brand_text}>
           Our Top Partners
          </div>
          <div className={styles.brand_imgs}>
             <div className={styles.img_card}>
               <Image src={artoon} alt="artoon" />
             </div>
             <div className={styles.img_card}>
               <Image src={collect} alt="collect" />
             </div>
             <div className={styles.img_card}>
               <Image src={affel} alt="affel" />
             </div>
             <div className={styles.img_card}>
               <Image src={inmobi} alt="inmobi" />
             </div>
             <div className={styles.img_card}>
               <Image src={gala} alt="gala" />
             </div>
             <div className={styles.img_card}>
               <Image src={jump} alt="gala" />
             </div>
          </div>
        </Barnds>
        <Barnds bgImg>
        <div className={styles.brand_text}>
           Our Top Clients
          </div>
          <div className={styles.brand_imgs}>
             <div className={styles.img_card}>
               <Image src={artoon} alt="artoon" />
             </div>
             <div className={styles.img_card}>
               <Image src={artoon} alt="artoon" />
             </div>
             <div className={styles.img_card}>
               <Image src={artoon} alt="artoon" />
             </div>
            </div>
        </Barnds>
        <Testo/>
      </main>

      <footer className={styles.footer}>
         <div className={styles.footer_text}>Acquire <span className={styles.underline}>quality users</span>, not just installs</div>
         <p>Talk to us today and start creating mobile marketing campaigns that deliver results.</p>
      </footer>
      <p className={styles.copy}>©2022 GreedyGame, Inc. All rights reserved.</p>
    </div>
  )
}
